version: '2'

services:

  7.0-fpm:
    build:  ./7.0/fpm
    image:  cubicmushroom/php:7.0-fpm

  7.0-fpm-dev:
    build:  ./7.0/fpm/dev
    image:  cubicmushroom/php:7.0-fpm-dev
    depends_on:
      - 7.0-fpm